### ISSUE TITLE
Problem when run

### ISSUE THREAD

**Issue by Doujinx** [techgaun/github-dorks#56]
$ python3 github-dork.py -r https://github.com/techgaun/github-dorks
Traceback (most recent call last):
  File "/home/kali/Programs/github-dorks/github-dork.py", line 4, in <module>
    import github3 as github
  File "/home/kali/.local/lib/python3.11/site-packages/github3/__init__.py", line 18, in <module>
    from .api import (
  File "/home/kali/.local/lib/python3.11/site-packages/github3/api.py", line 11, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/home/kali/.local/lib/python3.11/site-packages/github3/github.py", line 13, in <module>
    from .auths import Authorization
  File "/home/kali/.local/lib/python3.11/site-packages/github3/auths.py", line 12, in <module>
    from .models import GitHubCore
  File "/home/kali/.local/lib/python3.11/site-packages/github3/models.py", line 19, in <module>
    from .session import GitHubSession
  File "/home/kali/.local/lib/python3.11/site-packages/github3/session.py", line 4, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

Can you help me with that ?

**Comment by techgaun** [comment]
Thanks for the report. Maybe its not working with python 3.11. I'll check it sometime coming weekend and see if I can get a fix out.

**Comment by 4auvar** [comment]
Hi There,

I have also faced the same problem. This seems like an issue with latest python version and code of github3 package. 
I have python3.10 installed.

so the solution is to change 2 files:
one is '~/.local/lib/python3.10/site-packages/github3/session.py' and 
other one is `~/.local/lib/python3.10/site-packages/github3/structs.py`

in session.py file search & replace `from collections import Callable` with `from collections.abc import Callable`

and in structs.py file search & replace `class GitHubIterator(models.GitHubCore, collections.Iterator):` with `class GitHubIterator(models.GitHubCore, collections.abc.Iterator):`


I hope this helps.

**Comment by dbfreem** [comment]
@techgaun this issue should be able to be closed now that #58 is merged.

**Comment by techgaun** [comment]
Thanks closing as fixed by #58
